// This file is auto-generated by GraphQL code generator
// Don't edit this file manually

export interface GetCostPredictionDataQuery {
  cloudAccount: {
    id: string;
    name: string;
    expenses: Array<{
      day: string;
      cost: number;
    }>;
  };
}

export interface GetCostPredictionDataQueryVariables {
  dataSourceId: string;
  startDate: string;
  endDate: string;
}
